# Generated by Django 5.2 on 2025-12-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_grade_remove_question_category_subject_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='taught_grades',
            field=models.ManyToManyField(blank=True, help_text='Энэ багш хариуцдаг ангиуд', related_name='teachers', to='questions.grade', verbose_name='Хариуцдаг ангиуд'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='taught_subjects',
            field=models.ManyToManyField(blank=True, help_text='Энэ багш хариуцдаг хичээлүүд', related_name='teachers', to='questions.subject', verbose_name='Хариуцдаг хичээлүүд'),
        ),
    ]
